# Node server buildspec
# Used by AWS CodeDeploy
version: 0.0
os: linux
files:
  - source: server
    destination: /home/ec2-user/mugbug-app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - locaton: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
