version: "3.8"
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    # environment:
  server:
    build: ./server
    ports:
      - 9000:9000
    depends_on:
      - database
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: mydb
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - .server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - .serber/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
