version: "3.8"
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 9000:9000
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mugbug-0
    volumes:
      - ./db-data:/var/lib/postgresql/data
      # - ./server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
